### ISSUE TITLE
No able to disable set_error_handler, no way to set custom error handler

### ISSUE THREAD

**Issue by Insality** [indiesoftby/defold-sentinel#6]
**Describe the bug**
Seems I'm no able to disable auto set_error_handler:

```lua
    -- Default settings
    M.config.send_timeout = M.config.send_timeout or 30 -- seconds
    M.config.set_error_handler = M.config.set_error_handler or true
    M.config.load_previous_crash = M.config.load_previous_crash or true
```
(I mean the code `M.config.set_error_handler or true` is always true ;))

I use my own `sys_error_handler` and I want to trigger errors with custom traceback by myself

**Comment by aglitchman** [comment]
Fixed in [the 1.1.1 release](https://github.com/indiesoftby/defold-sentinel/releases/tag/1.1.1).

Thanks a million! 🙌

**Comment by Insality** [comment]
Thanks!

But since we can disable set_error_handlers in sentry, can you give the ability to invoke it by myself?
I mean make the `error_handler` function public? Or another way to do this?

**Comment by aglitchman** [comment]
> Or another way to do this?

In fact, `error_handler` simply calls `sentry.capture_exception`:

```lua
local function error_handler(source, message, traceback)
    local error = {source = source, message = message, traceback = traceback}
    local pstatus, perr = pcall(M.capture_exception, error)
    if not pstatus then
        log_print("Exception capture error " .. perr)
    end

    if M.config.on_soft_crash then
        pstatus, perr = pcall(M.config.on_soft_crash, error)
        log_print("Soft crash callback error " .. perr)
    end
end
```

I don't want to expose `error_handler` to keep API as simple as possible. From my view, there are two ways to do what you want:
1. Set `config.on_soft_crash` handler to do something custom in the error handler.
2. **(my preference)** Use your own error handler and just call `sentry.capture_exception` like that:

```lua
local function my_error_handler(source, message, traceback)
    local error = {source = source, message = message, traceback = traceback}

    -- ... custom code ...

    local pstatus, perr = pcall(sentry.capture_exception, error)
    if not pstatus then
        log_print("Exception capture error " .. perr)
    end
end

-- ...

sys.set_error_handler(my_error_handler)
```

**Comment by Insality** [comment]
Ohh, my bad! You are fully right! I don't look up closely to this

Thanks for the answer, it can suit now any wishes :)
